"""add sender_name and suggested_actions

Revision ID: a5252ccaf39f
Revises: f9bc35c961ad
Create Date: 2026-03-23 17:37:19.652860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5252ccaf39f'
down_revision: Union[str, None] = 'f9bc35c961ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('sender_name', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('suggested_actions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'suggested_actions')
    op.drop_column('emails', 'sender_name')
    # ### end Alembic commands ###
