"""add sender_name and suggested_actions

Revision ID: e2dcba622d07
Revises: a5252ccaf39f
Create Date: 2026-03-23 17:37:37.785445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2dcba622d07'
down_revision: Union[str, None] = 'a5252ccaf39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
