export const dynamic = "force-dynamic";
import { NextResponse } from 'next/server';
import { getData } from '@/lib/dataLoader';

export async function GET() {
  try {
    const data = await getData();
    const { stats, merchantFraud, cityFraud, repeatOffenders, impossibleTravel } = data;

    const cryptoFraud = merchantFraud.find((m) => m.name === 'Crypto Exchange');
    const electronicsFraud = merchantFraud.find((m) => m.name === 'Electronics');
    const topOffenders = repeatOffenders.slice(0, 10);
    const topCities = cityFraud.slice(0, 3);

    const markdown = `# FraudShield Business Insights Summary

## Executive Summary

Analysis of **${stats.totalTransactions.toLocaleString()} transactions** revealed **${stats.flaggedCount} fraud cases** (${stats.fraudRate.toFixed(3)}% fraud rate). This report identifies critical patterns and recommends immediate actions.

---

## Key Findings

### 1. The $500 Rule (Critical Discovery)

**100% of fraud occurs on transactions above $500.**

- Minimum flagged amount: $502.33
- Maximum flagged amount: $2,499.42
- Zero fraud cases below $500 threshold

**Recommendation:** Implement mandatory review for all transactions ≥$500. This single rule would have caught every fraud case in this dataset.

---

### 2. High-Risk Merchant Categories

| Category | Total Transactions | Fraud Cases | Fraud Rate |
|----------|------------|-------------|------------|
| Crypto Exchange | ${cryptoFraud?.total.toLocaleString() || 'N/A'} | ${cryptoFraud?.fraud || 0} | **${cryptoFraud?.rate || 0}%** |
| Electronics | ${electronicsFraud?.total.toLocaleString() || 'N/A'} | ${electronicsFraud?.fraud || 0} | **${electronicsFraud?.rate || 0}%** |
| Groceries | 59,000+ | 0 | 0% |
| Dining | 49,000+ | 0 | 0% |
| Retail | 40,000+ | 0 | 0% |
| Travel | 20,000+ | 0 | 0% |

**Recommendation:** Add friction (2FA, cooling period) for Crypto Exchange and Electronics purchases above $500.

---

### 3. Weekend & Night Pattern

- **${stats.weekendFraudPercent}% of fraud occurs on weekends** (Saturday/Sunday)
- **Peak fraud hour: ${stats.peakFraudHour}:00** (${stats.peakFraudHour < 12 ? stats.peakFraudHour + ' AM' : (stats.peakFraudHour - 12) + ' PM'})
- Friday-Sunday, midnight-6 AM = highest risk window

**Recommendation:** Enhanced monitoring and reduced auto-approval thresholds during high-risk windows.

---

### 4. Repeat Offenders (Urgent)

**${repeatOffenders.length} users have been flagged 2+ times.** Top offenders:

| User ID | Flag Count | Total Amount |
|---------|------------|--------------|
${topOffenders.map((o) => `| ${o.userId} | ${o.flagCount} | $${o.totalAmount.toLocaleString()} |`).join('\n')}

**Critical Issue:** These accounts remain active despite multiple fraud flags.

**Recommendation:** Auto-freeze accounts after 3 fraud flags. Review and close accounts listed above.

---

### 5. Impossible Travel Detection

**${impossibleTravel.length} cases** of same user transacting in different cities within 60 minutes.

Example: User appearing in Dubai and London within 3 minutes.

**Recommendation:** Deploy real-time velocity checks. Flag transactions where user location changes faster than physically possible.

---

### 6. Geographic Hotspots

| City | Fraud Cases | Fraud Rate |
|------|-------------|------------|
${topCities.map((c) => `| ${c.city} | ${c.fraud} | ${c.rate}% |`).join('\n')}

---

## Recommended Actions (Priority Order)

1. **Immediate:** Freeze accounts with 3+ fraud flags
2. **This Week:** Implement $500 review threshold
3. **This Month:** Add 2FA for Crypto/Electronics >$500
4. **Ongoing:** Deploy impossible travel detection
5. **Ongoing:** Enhanced weekend/night monitoring

---

## ROI Estimate

If the $500 review threshold had been in place:
- **669 fraud cases** would have been reviewed before approval
- Potential savings: **$500,000+** in fraud losses (estimated)

---

*Generated by FraudShield Analytics*
*Data period: Full transaction history (${stats.totalTransactions.toLocaleString()} transactions)*
`;

    return new Response(markdown, {
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': 'attachment; filename="FraudShield-Business-Summary.md"',
      },
    });
  } catch (error) {
    console.error('Error generating one-pager:', error);
    return NextResponse.json(
      { error: 'Failed to generate business summary' },
      { status: 500 }
    );
  }
}
